name: claw_machine
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dart_periphery:
    git:
      url: https://github.com/ookami-kb/dart_periphery.git
      ref: pn532-fix
  fast_immutable_collections: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  ndef: ^0.3.1
  shared_preferences: ^2.0.20

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  mews_pedantic: ^0.13.0

flutter:
  uses-material-design: true
